name: lexi
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.08.22=hecd8cb5_0
  - libffi=3.4.4=hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.12=hca72f7f_0
  - pip=23.3=py310hecd8cb5_0
  - python=3.10.13=h5ee71fb_0
  - readline=8.2=hca72f7f_0
  - setuptools=68.0.0=py310hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - tk=8.6.12=h5d9f67b_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.41.2=py310hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - annotated-types==0.6.0
    - anthropic==0.7.6
    - anyio==3.7.1
    - appdirs==1.4.4
    - astroid==3.0.1
    - beautifulsoup4==4.12.2
    - bs4==0.0.1
    - certifi==2023.11.17
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - configobj==5.0.8
    - cssselect==1.2.0
    - dill==0.3.7
    - distro==1.8.0
    - exceptiongroup==1.1.3
    - filelock==3.13.1
    - fsspec==2023.10.0
    - goose3==3.1.17
    - h11==0.14.0
    - html5lib==1.1
    - httpcore==1.0.2
    - httpx==0.25.1
    - huggingface-hub==0.19.4
    - idna==3.4
    - iniconfig==2.0.0
    - isort==5.13.1
    - jedi==0.19.1
    - jieba==0.42.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - langdetect==1.0.9
    - lxml==4.9.3
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - networkx==3.2.1
    - nltk==3.8.1
    - numpy==1.26.2
    - openai==1.3.6
    - packaging==23.2
    - parso==0.8.3
    - pebble==5.0.3
    - pillow==10.1.0
    - platformdirs==4.1.0
    - pluggy==1.3.0
    - prompt-toolkit==3.0.41
    - ptpython==3.0.23
    - pyahocorasick==2.0.0
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - pygments==2.17.2
    - pylint==3.0.3
    - pytest==7.4.3
    - python-dateutil==2.8.2
    - pyyaml==6.0.1
    - regex==2023.10.3
    - requests==2.31.0
    - rich==13.7.0
    - safetensors==0.4.1
    - six==1.16.0
    - sniffio==1.3.0
    - socksio==1.0.0
    - soupsieve==2.5
    - sympy==1.12
    - tiktoken==0.5.1
    - tokenizers==0.15.0
    - tomli==2.0.1
    - tomlkit==0.12.3
    - torch==2.1.1
    - tqdm==4.66.1
    - transformers==4.35.2
    - typing-extensions==4.8.0
    - urllib3==2.1.0
    - wcwidth==0.2.12
    - webencodings==0.5.1
